vim.pack.add({
    "https://github.com/rafamadriz/friendly-snippets",
    "https://www.github.com/moyiz/blink-emoji.nvim",
    "https://www.github.com/ellisonleao/gruvbox.nvim",
    "https://github.com/folke/which-key.nvim",
    "https://github.com/nvim-lua/plenary.nvim",
    "https://github.com/MunifTanjim/nui.nvim",
    "https://github.com/nvim-tree/nvim-web-devicons",
})
